apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  password: cXdlcnR5MTIz
