apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-helm.fullname" . }}
  namespace: {{ .Values.namespace }}  
  labels:
    {{- include "jenkins-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: master
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: slave
      port: {{ .Values.service.testport }}
      targetPort: {{ .Values.service.testport }}
  selector:
    {{- include "jenkins-helm.selectorLabels" . | nindent 4 }}
